### ISSUE TITLE
Revise UI scaling to maximise workspace

### ISSUE THREAD

**Issue by astrochili** [Insality/panthera#10]
Now scaling is applied on the small side of the window to fit everything. But with equal proportions, different window sizes produce the same picture.

If the user wants to expand the working area, he can't do it, because his interface just gets larger. Perhaps binding to screen pixels, as it works in regular software, would be more convenient, and the scale could be adjusted somewhere in the menu (50%...100%...200%).

**Comment by Insality** [comment]
In current Panthera you can use the next hotkeys to UI scaling:

Ctrl + Shift + - | Scale Panthera UI down
-- | --
Ctrl + Shift + + | Scale Panthera UI up

More Hotkeys here:
https://github.com/Insality/panthera/blob/main/docs_editor/hotkeys.md

**Comment by Insality** [comment]
In next release I planned to add also ability to expand the node list view and timeline view as more useful part of UI:


https://github.com/user-attachments/assets/852582e3-6f1f-4c68-b686-cd349a83341d

**Comment by astrochili** [comment]
Looks good!

**Comment by Insality** [comment]
Done in https://github.com/Insality/panthera/releases/tag/editor.804

**Comment by astrochili** [comment]
Work good! But two questions:
1) Why not the "resize arrow" cursor?
2) Are there plans to add this functionality to the right panel?

**Comment by Insality** [comment]
1. Field for improvements :) Required to make a custom cursors and load them and test on all platforms, so probably later

2. Yea, since need to improve in general resizing. With the right panel a lot of issues happens now. So hope in the next releases I got how to fix all of them

**Comment by astrochili** [comment]
1 Hm! I thought the OS has this API, i.e. Windows / macOS have these cursor states as I know. Maybe DefOS doesn't provide it.

**Comment by Insality** [comment]
Yea, defos provide a minimal set of cursor with ability to create&load cursor

So at least now users can see the clickable size with the hand cursor and it's enough for start
