### ISSUE TITLE
Don't move child nodes inside parents if both are selected

### ISSUE THREAD

**Issue by astrochili** [Insality/panthera#5]
When selecting all nodes in the tree - it would be great to move everything only globally as the solid structure, otherwise moving child nodes (if they are also selected with parents) is done twice or more, depending on the hierarchy level.

**Comment by mtuprikov-ms** [comment]
This is actually good thing!

**Comment by Insality** [comment]
This is actually a good thing!

**Comment by Insality** [comment]
Done in https://github.com/Insality/panthera/releases/tag/editor.804

**Comment by astrochili** [comment]
Superbl!
