### ISSUE TITLE
Import from and export to `*.collection` file

### ISSUE THREAD

**Issue by astrochili** [Insality/panthera#7]
It's possible to animate game objects, yeap. But for this you need to manually restore the tree of objects with their visual parameters in panthera, so that they correspond to the tree and parameters in Defold collection.

If there will be import of `*.collection` files, as well as their export to `*.collection` file, it will allow to make simple animations of game characters. Like a very lightweight Spine with a primitive bone system and uniform deformations.

An example of what I did in panthera from scratch just for fun, but didn't realise yet that I couldn't export and sync this objects tree with Defold:

https://github.com/user-attachments/assets/eaf35de6-ea7f-4fc6-8c00-3d38e1f75055

**Comment by Insality** [comment]
Here is a little demo of this! Hope drop it soon

https://github.com/user-attachments/assets/86d11c73-296c-4307-bf83-5237d41aa36b

**Comment by Insality** [comment]
Done in https://github.com/Insality/panthera/releases/tag/editor.804
