### ISSUE TITLE
Import from and export to `*.atlas` file (or work with that directly)

### ISSUE THREAD

**Issue by astrochili** [Insality/panthera#8]
Maybe I haven't fully figured it out, but it seemed to me that the concept of "atlas" in Panthera is not at all related to atlases in Defold.

If there is already a Defold atlas, it would be convenient to import it and immediately get a full list of available images.

It would also be good to add new pictures to this atlas directly in Panthera, then save and export it, so that it would be updated in Defold version as well.

Perhaps it makes sense to switch to working with `*.atlas` files directly, without the middle `*.json` file.

**Comment by astrochili** [comment]
Aww, I didn't know that when importing a gui it also imports the linked atlas, that's great!

**Comment by Insality** [comment]
Won't change a current approach

Will keep it as a auto-export option, when working with gui/collections
