### ISSUE TITLE
A required delay when pressing `Cmd` key to trigger shortcuts like `Cmd + Z`

### ISSUE THREAD

**Issue by astrochili** [Insality/panthera#9]
If on macOS you quickly press `Cmd+Z`, `Cmd+S` or a similar shortcut, as I usually do in the rest of 99% of software, nothing happens. Patrena requires more calm pressing, some delay in pressing `Cmd` so that the modifier is taken into account when pressing the next key, otherwise they get out of sync and are pressed "one after another".

I don't know exactly where the problem is here - in Panthera or in Defold. If in Defold, it can be solved by adding some short timer after releasing the modifier key.

**Comment by Insality** [comment]
Done in https://github.com/Insality/panthera/releases/tag/editor.804

Hotkeys should be handled a little bit better, please report how it feels

**Comment by astrochili** [comment]
Works perfect! now Thanks!
